#!/bin/bash
git add LICENSE
git add *.md
git add gitpush
git add project/*
git add project/libApao/*
git add project/documents/*
git commit -m "more basic expression nodes"
git push origin master




