#!/bin/bash
git add LICENSE
git add *.md
git add gitpush
git add project/*
git add project/libApao/*
git add project/documents/*
git commit -m "Indexer (pointer variable pointing to other variable)"
git push origin master




